gen saturday = (dayoftheweek == 0 )
gen sunday = (dayoftheweek == 1 )
gen monday = (dayoftheweek == 2 )
gen tuesday = (dayoftheweek == 3 )
gen wednesday = (dayoftheweek == 4 )
gen thursday = (dayoftheweek == 5 )
gen friday = (dayoftheweek == 6 )

gen am12 = (houroftheday ==0)
gen am1 = (houroftheday ==1)
gen am2 = (houroftheday ==2)
gen am3 = (houroftheday ==3)
gen am4 = (houroftheday ==4)
gen am5 = (houroftheday ==5)
gen am6 = (houroftheday ==6)
gen am7 = (houroftheday ==7)
gen am8 = (houroftheday ==8)
gen am9 = (houroftheday ==9)
gen am10 = (houroftheday ==10)
gen am11 = (houroftheday ==11)
gen pm12 = (houroftheday ==12)
gen pm1 = (houroftheday ==13)
gen pm2 = (houroftheday ==14)
gen pm3 = (houroftheday ==15)
gen pm4 = (houroftheday ==16)
gen pm5 = (houroftheday ==17)
gen pm6 = (houroftheday ==18)
gen pm7 = (houroftheday ==19)
gen pm8 = (houroftheday ==20)
gen pm9 = (houroftheday ==21)
gen pm10 = (houroftheday ==22)
gen pm11 = (houroftheday ==23)

reg itemonorder saturday sunday monday tuesday wednesday thursday friday am12 am1 am2 am3 am4 am5 am6 am7 am8 am9 am10 am11 pm12 pm1 pm2 pm3 pm4 pm5 pm6 pm7 pm8 pm9 pm10 pm11 numofreordered
